image: node:slim

cache:
  paths:
    - node_modules/

pages:
  script:
    - npm ci
    - npm run build
    - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\|png\)$' -exec gzip -f -k {} \;
  artifacts:
    paths:
      - public
  only:
    - main
